#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Cache Packages

on:
  repository_dispatch:
    types: [cache]
  workflow_dispatch:
  schedule:
    - cron: 0 18 * * *

env:
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-18.06-k5.4

jobs:
  Build:
    runs-on: cache

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Clone Source Code
        run: |
          df -hT $PWD
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt

      - name: Install Feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Download All Packages
        run: |
          cd openwrt
          echo "CONFIG_ALL=y" >> .config
          make defconfig
          make download -j32 IGNORE_ERRORS=1
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
          mkdir -p /data/cache
          rm -rf /data/cache/dl
          mv dl /data/cache

